Class {
	#name : 'SlmdUserActionModel',
	#superclass : 'SlmdModel',
	#instVars : [
		'id',
		'actionGroup',
		'iconName',
		'iconLabel',
		'actionName',
		'arg1'
	],
	#category : 'CodeParadise-MaterialDesign-ShoelaceComponents',
	#package : 'CodeParadise-MaterialDesign',
	#tag : 'ShoelaceComponents'
}

{ #category : 'accessing' }
SlmdUserActionModel >> actionGroup [

	^ actionGroup
]

{ #category : 'accessing' }
SlmdUserActionModel >> actionGroup: anObject [

	actionGroup := anObject
]

{ #category : 'accessing' }
SlmdUserActionModel >> actionName [

	^ actionName
]

{ #category : 'accessing' }
SlmdUserActionModel >> actionName: anObject [

	actionName := anObject
]

{ #category : 'accessing' }
SlmdUserActionModel >> arg1 [

	^ arg1
]

{ #category : 'accessing' }
SlmdUserActionModel >> arg1: anObject [

	arg1 := anObject
]

{ #category : 'accessing' }
SlmdUserActionModel >> iconLabel [

	^ iconLabel
]

{ #category : 'accessing' }
SlmdUserActionModel >> iconLabel: anObject [

	iconLabel := anObject
]

{ #category : 'accessing' }
SlmdUserActionModel >> iconName [

	^ iconName
]

{ #category : 'accessing' }
SlmdUserActionModel >> iconName: anObject [

	iconName := anObject
]

{ #category : 'accessing' }
SlmdUserActionModel >> id [

	^ id
]

{ #category : 'accessing' }
SlmdUserActionModel >> id: anObject [

	id := anObject
]
