Class {
	#name : 'WamListModel',
	#superclass : 'WamModel',
	#category : 'CodeParadise-MaterialDesign-ListDetail',
	#package : 'CodeParadise-MaterialDesign',
	#tag : 'ListDetail'
}

{ #category : 'accessing' }
WamListModel >> list [

	self subclassResponsibility

]

{ #category : 'accessing' }
WamListModel >> list: anObject [

	self subclassResponsibility

]

{ #category : 'accessing' }
WamListModel >> listSet: aCollection [

	self subclassResponsibility

]

{ #category : 'accessing' }
WamListModel >> modelWrapperClass [

	self subclassResponsibility

]
