Class {
	#name : 'SlmdDemoAccountingUserCompany',
	#superclass : 'SlmdDemoObject',
	#instVars : [
		'id',
		'userId',
		'companyId'
	],
	#category : 'CodeParadise-Examples-MD3-Accounting',
	#package : 'CodeParadise-Examples-MD3',
	#tag : 'Accounting'
}

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> companyId [

	^ companyId
]

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> companyId: anObject [

	companyId := anObject
]

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> id [

	^ id
]

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> id: anObject [

	id := anObject
]

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> userId [

	^ userId
]

{ #category : 'accessing' }
SlmdDemoAccountingUserCompany >> userId: anObject [

	userId := anObject
]
