Class {
	#name : 'SlmdDemoAccountingAppClientBehavior',
	#superclass : 'WamWebClientBehavior',
	#category : 'CodeParadise-Examples-MD3-Accounting',
	#package : 'CodeParadise-Examples-MD3',
	#tag : 'Accounting'
}

{ #category : 'accessing' }
SlmdDemoAccountingAppClientBehavior >> appName [

	^ 'Accounting'
]

{ #category : 'accessing' }
SlmdDemoAccountingAppClientBehavior >> appTagName [

	^ 'slmd-demo-accounting-app'
]
