Class {
	#name : 'WamDemoAccountingUserCompany',
	#superclass : 'WamDemoObject',
	#instVars : [
		'id',
		'userId',
		'companyId'
	],
	#category : 'CodeParadise-Examples-MD3-Accounting',
	#package : 'CodeParadise-Examples-MD3',
	#tag : 'Accounting'
}

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> companyId [

	^ companyId
]

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> companyId: anObject [

	companyId := anObject
]

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> id [

	^ id
]

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> id: anObject [

	id := anObject
]

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> userId [

	^ userId
]

{ #category : 'accessing' }
WamDemoAccountingUserCompany >> userId: anObject [

	userId := anObject
]
