Class {
	#name : 'WamDemoAccountingAppClientBehavior',
	#superclass : 'WamWebClientBehavior',
	#category : 'CodeParadise-Examples-MD3-Accounting',
	#package : 'CodeParadise-Examples-MD3',
	#tag : 'Accounting'
}

{ #category : 'accessing' }
WamDemoAccountingAppClientBehavior >> appName [

	^ 'Accounting'
]

{ #category : 'accessing' }
WamDemoAccountingAppClientBehavior >> appTagName [

	^ 'wam-demo-accounting-app'
]
